name: Kernel Build CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ARCH: arm64
      CC: clang
      CLANG_TRIPLE: aarch64-linux-gnu-

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update

      - name: Build the kernel and log output
        run: |
          ./build.sh | tee build.log
